# Generated by Django 3.0.2 on 2020-01-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='aut_hor',
            new_name='author',
        ),
        migrations.AddField(
            model_name='userdata',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='extra_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='votefact',
            name='answer',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votevariant',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='votevariant',
            name='vote_fact_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voting',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voting',
            name='show_votes_before_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voting',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voting',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voting',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votingabuse',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
