# Generated by Django 3.0.1 on 2020-01-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191226_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='author',
        ),
    ]
