# Generated by Django 3.0.2 on 2020-01-09 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_voting_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='date_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 9, 15, 44, 31, 291685)),
        ),
        migrations.AddField(
            model_name='voting',
            name='date_stopped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 9, 15, 44, 31, 291685)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 9, 15, 44, 31, 291685)),
        ),
    ]
