# Generated by Django 3.0.2 on 2020-01-18 12:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20200115_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('pause', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 15, 30, 52, 272407))),
                ('author', models.ForeignKey(on_delete=models.SET(main.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 15, 30, 52, 272407)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 15, 30, 52, 272407)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_stopped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 15, 30, 52, 272407)),
        ),
        migrations.CreateModel(
            name='VotingSetAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.VotingSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
