# Generated by Django 3.0.2 on 2020-01-18 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200118_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.VotingSet'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 15, 39, 56, 864949)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 15, 39, 56, 864949)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_stopped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 15, 39, 56, 864949)),
        ),
        migrations.AlterField(
            model_name='votingset',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 18, 15, 39, 56, 864949)),
        ),
    ]
