# Generated by Django 3.0.2 on 2020-01-21 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200119_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 21, 7, 21, 24, 513193)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 21, 7, 21, 24, 513193)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_stopped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 21, 7, 21, 24, 513193)),
        ),
    ]
