# Generated by Django 3.0.2 on 2020-01-19 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200119_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingset',
            name='author',
        ),
        migrations.RemoveField(
            model_name='votingset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='votingset',
            name='title',
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 19, 13, 4, 36, 702583)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 19, 13, 4, 36, 702583)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_stopped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 19, 13, 4, 36, 702583)),
        ),
        migrations.AlterField(
            model_name='votingset',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 19, 13, 4, 36, 702583)),
        ),
    ]
