# Generated by Django 3.0.2 on 2020-01-19 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200119_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingset',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 19, 13, 6, 37, 993101)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 19, 13, 6, 37, 993101)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_stopped',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 19, 13, 6, 37, 993101)),
        ),
    ]
